# [sinks.cdviz_db]
# enabled = true
# type = "db"
# url = "postgresql://postgres:passwd@localhost:5432/cdviz"
# pool_connections_min = 1
# pool_connections_max = 10

[sinks.cdevents_local_json]
enabled = false
parameters = { root = "./sinks.off" }

[sources.cdevents_local_json]
enabled = true

[sources.cdevents_local_json.extractor]
parameters = { root = "./inputs/cdevents_json" }

[sources.cdevents_local_csv]
enabled = true
transformer_refs = ["service_deployed"]

[sources.cdevents_local_csv.extractor]
type = "opendal"
kind = "fs"
polling_interval = "10s"
parameters = { root = "./inputs" }
recursive = false
path_patterns = ["cdevents.csv"]
parser = "csv_row"

[sources.cdevents_webhook]
enabled = true
# type = "http"

[transformers.service_deployed]
type = "vrl"
template = """
[{
    "metadata": .metadata,
    "header": .header,
    "body": {
        "context": {
            "version": "0.4.0-draft",
            "id": "0",
            "source": "/event/source/123",
            "type": "dev.cdevents.service.deployed.0.1.1",
            "timestamp": .body.timestamp,
        },
        "subject": {
            "id": .body.id,
            "source": "/event/source/123",
            "type": "service",
            "content": {
                "environment": {
                    "id": .body.env,
                },
                "artifactId": .body.artifact_id,
            }
        }
    }
}]
"""

[sources.github_local_json]
enabled = true
transformer_refs = ["github_events"]

[sources.github_local_json.extractor]
type = "opendal"
kind = "fs"
parameters = { root = "./inputs/github_events" }
polling_interval = "10s"
recursive = true
path_patterns = ["**/*.json"]
parser = "json"

[sources.github_webhook]
enabled = true
transformer_refs = ["github_events"]

[sources.github_webhook.extractor]
type = "webhook"
id = "001"
headers_to_keep = []
# token override by environment variable reads from the secret
signature = { signature_encoding = "hex", signature_on = "body", signature_prefix = "sha256=", header = "x-hub-signature-256", token = "changeme" }

[transformers.github_events]
type = "vrl"
template_file = "../../config/transformers/github_events.vrl"
