# [sinks.cdviz_db]
# enabled = true
# type = "db"
# url = "postgresql://postgres:passwd@localhost:5432/cdviz"
# pool_connections_min = 1
# pool_connections_max = 10

# [sinks.sse_001]
# # This will create an SSE endpoint at http://localhost:8080/sse/001
# enabled = false
# type = "sse"
# id = "001"
# headers = [
#   { header = "Authorization", rule = { type = "exists" } },
#   { header = "X-API-Key", rule = { type = "matches", pattern = "^[a-zA-Z0-9]{32}$" } }
# ]

[sinks.cdevents_local_json]
enabled = false
parameters = { root = "./sinks.off" }

[sources.cdevents_local_json]
enabled = true

[sources.cdevents_local_json.extractor]
parameters = { root = "./inputs/cdevents_json" }

[sources.cdevents_local_csv]
enabled = true
transformer_refs = ["service_deployed"]

[sources.cdevents_local_csv.extractor]
type = "opendal"
kind = "fs"
polling_interval = "10s"
parameters = { root = "./inputs" }
recursive = false
path_patterns = ["cdevents.csv"]
parser = "csv_row"

[sources.cdevents_webhook]
enabled = true
# type = "http"

[transformers.service_deployed]
type = "vrl"
template = """
[{
    "metadata": .metadata,
    "headers": .headers,
    "body": {
        "context": {
            "version": "0.4.0-draft",
            "id": "0",
            "source": "/event/source/123",
            "type": "dev.cdevents.service.deployed.0.1.1",
            "timestamp": .body.timestamp,
        },
        "subject": {
            "id": .body.id,
            "source": "/event/source/123",
            "type": "service",
            "content": {
                "environment": {
                    "id": .body.env,
                },
                "artifactId": .body.artifact_id,
            }
        }
    }
}]
"""

[sources.github_local_json]
enabled = true
transformer_refs = ["github_events"]

[sources.github_local_json.extractor]
type = "opendal"
kind = "fs"
parameters = { root = "./inputs/github_events" }
polling_interval = "10s"
recursive = true
path_patterns = ["**/*.json"]
parser = "json"

[sources.github_webhook]
enabled = true
transformer_refs = ["github_events"]

[sources.github_webhook.extractor]
type = "webhook"
id = "000-github"
headers_to_keep = []
# token override by environment variable reads from the secret
headers = [
#   { header = "Authorization", rule = { type = "exists" } },
#   { header = "X-API-Key", rule = { type = "matches", pattern = "^[a-zA-Z0-9]{32}$" } }
  { header = "x-hub-signature-256", rule = { type = "signature", signature_encoding = "hex", signature_on = "body", signature_prefix = "sha256=", token = "changeme" }}
]

[transformers.github_events]
type = "vrl"
template_file = "../../config/transformers/github_events.vrl"

[sources.kubewatch_webhook]
enabled = true
transformer_refs = [ "log", "kubewatch_metadata", "log", "kubewatch_cloudevents", "log" ]

[sources.kubewatch_webhook.extractor]
type = "webhook"
id = "000-kubewatch"

[transformers.kubewatch_metadata]
type = "vrl"
template = """
.metadata = object(.metadata) ?? {}

[{
  "metadata": merge(.metadata, {
    "environment_id": "cluster/A-dev",
  }),
  "headers": .headers,
  "body": .body,
}]
"""

[transformers.kubewatch_cloudevents]
type = "vrl"
template_file = "../../config/transformers/kubewatch_cloudevents.vrl"

[transformers.vrl_identity]
type = "vrl"
template = """
[.]
"""

[transformers.vrl_copy_l1]
type = "vrl"
template = """
[{
  "metadata": .metadata,
  "headers": .headers,
  "body": .body,
}]
"""


[sources.cdevents_sse]
enabled = false

[sources.cdevents_sse.extractor]
type = "sse"
url = "http://localhost:8080/sse/001"
# headers = [
#   { header = "Authorization", rule = { type = "static", value = "Bearer your-token-here" } },
#   { header = "X-API-Key", rule = { type = "secret", value = "your-api-key-from-env" } },
#   { header = "X-Signature-256", rule = { type = "signature", token = "webhook-secret", signature_prefix = "sha256=" } }
# ]
# max_retries = 10
