[sinks.debug]
enabled = true

[sinks.cdviz_db]
enabled = true
# type = "db"
# url = "postgresql://postgres:passwd@localhost:5432/cdviz"
# pool_connections_min = 1
# pool_connections_max = 10

[sources.cdevents_local_json]
enabled = true

[sources.cdevents_local_json.extractor]
parameters = { root = "./opendal_fs" }

[sources.cdevents_local_csv]
enabled = true

[sources.cdevents_local_csv.extractor]
parameters = { root = "./opendal_fs" }

[sources.cdevents_webhook.extractor]
enabled = true
# type = "http"
# host = "0.0.0.0"
# port = 8080
