[env]
RUSTC_WRAPPER = "sccache"
RUST_WITHOUT = "rust-docs"
# ASDF_RUST_PROFILE = "minimal"
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "http://127.0.0.1:4317"
# OTEL_EXPORTER_OTLP_TRACES_PROTOCOL = "grpc"
OTEL_TRACES_SAMPLER = "always_off"

[tools]
sccache = '0.8'
task = '3'                # to have a set of simple commands for repetive task (and CI)
rust = '1.77.0'           # the rust tool stack (with cargo, fmt, clippy) to build source
cargo-binstall = 'latest'

[plugins]
cargo-binstall = "https://github.com/davidB/asdf-cargo-binstall"
