[sinks.debug]
enabled = false
type = "debug"

[sinks.cdevents_local_json]
enabled = false
type = "folder"
kind = "fs"
parameters = { root = "./sink" }

[sinks.cdviz_db]
enabled = false
type = "db"
url = "postgresql://postgres:passwd@localhost:5432/cdviz"
pool_connections_min = 1
pool_connections_max = 10

[sources.cdevents_local_json]
enabled = false

[sources.cdevents_local_json.extractor]
type = "opendal"
kind = "fs"
polling_interval = "10s"
parameters = { root = "./source" }
recursive = true
path_patterns = ["**/*.json"]
parser = "json"

[sources.cdevents_webhook]
enabled = false

[sources.cdevents_webhook.extractor]
type = "http"
host = "0.0.0.0"
port = 8080

[transformers.passthrough]
type = "passthrough"

[transformers.log]
type = "log"
target = "transformers::log"

[transformers.discard_all]
type = "discard_all"
