---
# inspiration:
# - [Tips for Faster Rust CI Builds | corrode Rust Consulting](https://corrode.dev/blog/tips-for-faster-ci-builds/)
name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - "releases/*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    # "ubuntu-22.04-arm" faster? but fewer available than "ubuntu-latest"
    runs-on: "ubuntu-22.04-arm"
    env:
      CARGO_TERM_COLOR: always
      # to help debug on failure (maybe conflict with disable of test debug)
      RUST_BACKTRACE: full
      # reduce size of target (good for caching)
      CARGO_PROFILE_TEST_DEBUG: 0
      # disable incremental compilation faster from-scratch builds & sccache
      CARGO_INCREMENTAL: 0
      # configure sccache to cache the build artifacts (on github caches)
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.6
      - uses: jdx/mise-action@v2
      - run: mise install
        shell: bash
      - run: mise run --jobs 1 ci
        shell: bash
      - run: ${SCCACHE_PATH} --show-stats
        shell: bash
